class SPKModel {
  final String id,
      id_customer,
      id_admin,
      no_spk,
      ket_pekerjaan,
      keterangan,
      jam_mulai,
      jam_selesai,
      download_speed,
      upload_speed,
      ket_lanjutan,
      status,
      nama,
      jenis_layanan,
      no_telp,
      alamat,
      tgl_instalasi,
      tgl_trial,
      nama_admin,
      ikr;

  SPKModel(
      {this.id,
      this.id_customer,
      this.id_admin,
      this.no_spk,
      this.ket_pekerjaan,
      this.keterangan,
      this.jam_mulai,
      this.jam_selesai,
      this.download_speed,
      this.upload_speed,
      this.ket_lanjutan,
      this.status,
      this.nama,
      this.jenis_layanan,
      this.no_telp,
      this.alamat,
      this.tgl_instalasi,
      this.tgl_trial,
      this.nama_admin,
      this.ikr});

  factory SPKModel.fromJSON(Map<String, dynamic> object) {
    return SPKModel(
        id: object['id'],
        id_customer: object['id_customer'],
        id_admin: object['id_admin'],
        no_spk: object['no_spk'],
        ket_pekerjaan: object['ket_pekerjaan'],
        keterangan: object['keterangan'],
        jam_mulai: object['jam_mulai'],
        jam_selesai: object['jam_selesai'],
        download_speed: object['download_speed'],
        upload_speed: object['upload_speed'],
        ket_lanjutan: object['ket_lanjutan'],
        status: object['status'],
        nama: object['nama'],
        jenis_layanan: object['jenis_layanan'],
        no_telp: object['no_telp'],
        alamat: object['alamat'],
        tgl_instalasi: object['tgl_instalasi'],
        tgl_trial: object['tgl_trial'],
        nama_admin: object['nama_admin'],
        ikr: object['ikr']);
  }
}
